language: ruby
sudo: required
dist: xenial

cache:
  - bundler
  - npm

services:
  - redis-server
  - mysql

addons:
  postgresql: 10

rvm:
  - 2.5.5
  - 2.6.3
  - ruby-head

env:
  matrix:
    - CI=true CI_DB=sqlite GEMS=data

matrix:
  include:
    - language: ruby
      before_install:
        - gem update --system
        - gem install bundler
      script:
        - bundle exec rake

    - language: node_js
      node_js:
        - node
      before_install:
        - cd pakyow-js
      script:
        - npm test

  exclude:
    - rvm: ruby-head
      env: CI_BENCH=true
    - rvm: ruby-head
      env: CI_SMOKE=true

  allow_failures:
    - rvm: ruby-head
    - env: CI_BENCH=true

  fast_finish: true

notifications:
  email: false
